"""Add transit total/received quantity

Revision ID: 1a7e61123e0d
Revises: eeb566bab43f
Create Date: 2026-03-22 17:08:39.707864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7e61123e0d'
down_revision: Union[str, Sequence[str], None] = 'eeb566bab43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transit_inventory', sa.Column('total_quantity', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('transit_inventory', sa.Column('received_quantity', sa.Integer(), nullable=False, server_default='0'))
    op.execute("UPDATE transit_inventory SET total_quantity = quantity WHERE total_quantity IS NULL")
    op.alter_column('transit_inventory', 'total_quantity', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transit_inventory', 'received_quantity')
    op.drop_column('transit_inventory', 'total_quantity')
    # ### end Alembic commands ###
