"""Add contract_no to inbound_order

Revision ID: 3a872492799c
Revises: 18591cbbc70a
Create Date: 2026-03-22 14:11:31.977935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a872492799c'
down_revision: Union[str, Sequence[str], None] = '18591cbbc70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_order', sa.Column('contract_no', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound_order', 'contract_no')
    # ### end Alembic commands ###
