"""Add borrow orders

Revision ID: 7960916461ee
Revises: ea12277db953
Create Date: 2026-03-22 19:23:17.013230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7960916461ee'
down_revision: Union[str, Sequence[str], None] = 'ea12277db953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrow_no', sa.String(length=50), nullable=False),
    sa.Column('borrower', sa.String(length=100), nullable=False),
    sa.Column('borrower_unit', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('borrow_time', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_order_borrow_no'), 'borrow_order', ['borrow_no'], unique=True)
    op.create_index(op.f('ix_borrow_order_id'), 'borrow_order', ['id'], unique=False)
    op.create_index(op.f('ix_borrow_order_status'), 'borrow_order', ['status'], unique=False)
    op.create_table('borrow_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrow_order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('price_version_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('returned_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrow_order_id'], ['borrow_order.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['price_version_id'], ['material_price_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_item_borrow_order_id'), 'borrow_item', ['borrow_order_id'], unique=False)
    op.create_index(op.f('ix_borrow_item_id'), 'borrow_item', ['id'], unique=False)
    op.create_index(op.f('ix_borrow_item_location_id'), 'borrow_item', ['location_id'], unique=False)
    op.create_index(op.f('ix_borrow_item_material_id'), 'borrow_item', ['material_id'], unique=False)
    op.create_index(op.f('ix_borrow_item_price_version_id'), 'borrow_item', ['price_version_id'], unique=False)
    op.create_index(op.f('ix_borrow_item_status'), 'borrow_item', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_item_status'), table_name='borrow_item')
    op.drop_index(op.f('ix_borrow_item_price_version_id'), table_name='borrow_item')
    op.drop_index(op.f('ix_borrow_item_material_id'), table_name='borrow_item')
    op.drop_index(op.f('ix_borrow_item_location_id'), table_name='borrow_item')
    op.drop_index(op.f('ix_borrow_item_id'), table_name='borrow_item')
    op.drop_index(op.f('ix_borrow_item_borrow_order_id'), table_name='borrow_item')
    op.drop_table('borrow_item')
    op.drop_index(op.f('ix_borrow_order_status'), table_name='borrow_order')
    op.drop_index(op.f('ix_borrow_order_id'), table_name='borrow_order')
    op.drop_index(op.f('ix_borrow_order_borrow_no'), table_name='borrow_order')
    op.drop_table('borrow_order')
    # ### end Alembic commands ###
