"""Add inventory management models

Revision ID: 7f2164f553f9
Revises: a746a88d0146
Create Date: 2026-03-22 16:06:28.383236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2164f553f9'
down_revision: Union[str, Sequence[str], None] = 'a746a88d0146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_no', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_check_check_no'), 'inventory_check', ['check_no'], unique=True)
    op.create_index(op.f('ix_inventory_check_id'), 'inventory_check', ['id'], unique=False)
    op.create_table('inventory_check_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('price_version_id', sa.Integer(), nullable=False),
    sa.Column('system_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=True),
    sa.Column('difference', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['inventory_check.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['price_version_id'], ['material_price_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_check_item_id'), 'inventory_check_item', ['id'], unique=False)
    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_no', sa.String(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('price_version_id', sa.Integer(), nullable=False),
    sa.Column('source_location_id', sa.Integer(), nullable=False),
    sa.Column('target_location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('movement_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['price_version_id'], ['material_price_version.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['target_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movement_id'), 'stock_movement', ['id'], unique=False)
    op.create_index(op.f('ix_stock_movement_movement_no'), 'stock_movement', ['movement_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movement_movement_no'), table_name='stock_movement')
    op.drop_index(op.f('ix_stock_movement_id'), table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_index(op.f('ix_inventory_check_item_id'), table_name='inventory_check_item')
    op.drop_table('inventory_check_item')
    op.drop_index(op.f('ix_inventory_check_id'), table_name='inventory_check')
    op.drop_index(op.f('ix_inventory_check_check_no'), table_name='inventory_check')
    op.drop_table('inventory_check')
    # ### end Alembic commands ###
