"""Remove name, type, capacity from location

Revision ID: 84fd483a7a1a
Revises: 3a872492799c
Create Date: 2026-03-22 14:40:51.098165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fd483a7a1a'
down_revision: Union[str, Sequence[str], None] = '3a872492799c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'capacity')
    op.drop_column('location', 'type')
    op.drop_column('location', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
