"""Add area and row/layer/col to location

Revision ID: 888876f8f214
Revises: c13010a0e25e
Create Date: 2026-03-22 19:10:14.800083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888876f8f214'
down_revision: Union[str, Sequence[str], None] = 'c13010a0e25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('area_code', sa.String(length=50), nullable=True))
    op.add_column('location', sa.Column('row_no', sa.Integer(), nullable=True))
    op.add_column('location', sa.Column('layer_no', sa.Integer(), nullable=True))
    op.add_column('location', sa.Column('col_no', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_location_area_code'), 'location', ['area_code'], unique=False)
    op.create_index(op.f('ix_location_col_no'), 'location', ['col_no'], unique=False)
    op.create_index(op.f('ix_location_layer_no'), 'location', ['layer_no'], unique=False)
    op.create_index(op.f('ix_location_row_no'), 'location', ['row_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_row_no'), table_name='location')
    op.drop_index(op.f('ix_location_layer_no'), table_name='location')
    op.drop_index(op.f('ix_location_col_no'), table_name='location')
    op.drop_index(op.f('ix_location_area_code'), table_name='location')
    op.drop_column('location', 'col_no')
    op.drop_column('location', 'layer_no')
    op.drop_column('location', 'row_no')
    op.drop_column('location', 'area_code')
    # ### end Alembic commands ###
