"""Add total_inbound and total_outbound to stock

Revision ID: a746a88d0146
Revises: 84fd483a7a1a
Create Date: 2026-03-22 15:40:58.221205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a746a88d0146'
down_revision: Union[str, Sequence[str], None] = '84fd483a7a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('total_inbound', sa.Integer(), nullable=True))
    op.add_column('stock', sa.Column('total_outbound', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'total_outbound')
    op.drop_column('stock', 'total_inbound')
    # ### end Alembic commands ###
