"""Add transit inventory model

Revision ID: afaee3970c22
Revises: 7f2164f553f9
Create Date: 2026-03-22 16:20:23.270306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afaee3970c22'
down_revision: Union[str, Sequence[str], None] = '7f2164f553f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transit_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_no', sa.String(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_inventory_box_no'), 'transit_inventory', ['box_no'], unique=True)
    op.create_index(op.f('ix_transit_inventory_id'), 'transit_inventory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transit_inventory_id'), table_name='transit_inventory')
    op.drop_index(op.f('ix_transit_inventory_box_no'), table_name='transit_inventory')
    op.drop_table('transit_inventory')
    # ### end Alembic commands ###
