"""Add material category fields

Revision ID: c13010a0e25e
Revises: 741471c4d5f4
Create Date: 2026-03-22 18:57:10.744244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13010a0e25e'
down_revision: Union[str, Sequence[str], None] = '741471c4d5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('category_major', sa.String(length=100), nullable=True))
    op.add_column('material', sa.Column('category_minor', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_material_category_major'), 'material', ['category_major'], unique=False)
    op.create_index(op.f('ix_material_category_minor'), 'material', ['category_minor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_category_minor'), table_name='material')
    op.drop_index(op.f('ix_material_category_major'), table_name='material')
    op.drop_column('material', 'category_minor')
    op.drop_column('material', 'category_major')
    # ### end Alembic commands ###
