"""Add warehouse/zone/location codes to location

Revision ID: c5de25bd07b4
Revises: 0cf14b39c2c2
Create Date: 2026-03-22 18:22:56.923923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5de25bd07b4'
down_revision: Union[str, Sequence[str], None] = '0cf14b39c2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('warehouse_code', sa.String(length=50), nullable=True))
    op.add_column('location', sa.Column('zone_code', sa.String(length=50), nullable=True))
    op.add_column('location', sa.Column('location_code', sa.String(length=50), nullable=True))
    op.execute(
        "UPDATE location "
        "SET warehouse_code = split_part(code, '-', 1), "
        "    zone_code = split_part(code, '-', 2), "
        "    location_code = split_part(code, '-', 3) "
        "WHERE code ~ '^[^-]+-[^-]+-[^-]+$' "
        "  AND (warehouse_code IS NULL AND zone_code IS NULL AND location_code IS NULL)"
    )
    op.execute(
        "UPDATE location "
        "SET location_code = code "
        "WHERE location_code IS NULL"
    )
    op.create_index(op.f('ix_location_location_code'), 'location', ['location_code'], unique=False)
    op.create_index(op.f('ix_location_warehouse_code'), 'location', ['warehouse_code'], unique=False)
    op.create_index(op.f('ix_location_zone_code'), 'location', ['zone_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_zone_code'), table_name='location')
    op.drop_index(op.f('ix_location_warehouse_code'), table_name='location')
    op.drop_index(op.f('ix_location_location_code'), table_name='location')
    op.drop_column('location', 'location_code')
    op.drop_column('location', 'zone_code')
    op.drop_column('location', 'warehouse_code')
    # ### end Alembic commands ###
