"""Add outbound group_no

Revision ID: eeb566bab43f
Revises: fcf4fcb23da2
Create Date: 2026-03-22 16:57:17.372917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb566bab43f'
down_revision: Union[str, Sequence[str], None] = 'fcf4fcb23da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order', sa.Column('group_no', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_outbound_order_group_no'), 'outbound_order', ['group_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_order_group_no'), table_name='outbound_order')
    op.drop_column('outbound_order', 'group_no')
    # ### end Alembic commands ###
