"""Remove unique constraint on transit box_no

Revision ID: fcf4fcb23da2
Revises: afaee3970c22
Create Date: 2026-03-22 16:33:31.591717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf4fcb23da2'
down_revision: Union[str, Sequence[str], None] = 'afaee3970c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transit_inventory_box_no'), table_name='transit_inventory')
    op.create_index(op.f('ix_transit_inventory_box_no'), 'transit_inventory', ['box_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transit_inventory_box_no'), table_name='transit_inventory')
    op.create_index(op.f('ix_transit_inventory_box_no'), 'transit_inventory', ['box_no'], unique=True)
    # ### end Alembic commands ###
